# - - - - - - - - - - - - - - - - - - - - -
# Файл конфигурации для плагина RandomBox
# Автор плагина: saharNooby
# - - - - - - - - - - - - - - - - - - - - -
# Формат файла — YAML
# Для проверки правильности используйте
# http://yaml-online-parser.appspot.com/
# Если что-то пошло не так, то вы всегда
# можете удалить конфиг.
# - - - - - - - - - - - - - - - - - - - - -
# Режим debug включает вывод в консоль
# некоторого дерьма типа процентных
# соотношений.
# - - - - - - - - - - - - - - - - - - - - -
debug: false
# - - - - - - - - - - - - - - - - - - - - -
# Все коробки, доступные игрокам
# - - - - - - - - - - - - - - - - - - - - -
boxes:
  # Название коробки (указывается в команде /givebox <игрок> <id>)
  box1:
    # Вещь, которой является коробка, желательно, нестакающаяся.
    # Лучше всего подходит вагонетка с сундуком (STORAGE_MINECART).
    # Если эту вещь можно использовать (вагонетку, например, поставить на рельсы),
    # то это нельзя будет сделать, если эта вещь — коробка.
    # Формат указания: цифровой id (например, "57" — алмазный блок)
    # или строковый (для предыдущего — "DIAMOND_BLOCK").
    boxItem: STORAGE_MINECART
    # Название коробки
    boxName: Коробка бойца
    # Сколько вещей выпадает из коробки
    itemsToSelectCount: 3
    # Проверять наличие у открывающего разрешения randombox.open.<id коробки>
    checkPermission: false
    # Вещи, которые могут выпасть при открытии коробки
    items:
      # Любое название, не влияет ни на что
      item1:
        # id предмета
        item: DIAMOND_SWORD
        # Data value предмета (то, которое через двоеточие)
        data: 0
        # Количество предметов в стаке
        amount: 1
        # Название предмета (может быть цветным)
        # Обязательный параметр! Иначе не будет имени предмета
        # в описании к коробке.
        name: §cАлмазный меч
        # Описание предмета
        # Каждая строчка — отдельный пункт
        # - 'текст строки'
        lore:
        - §7Этот меч выпал
        - §7из коробки удачи.
        # Зачарования любого уровня и типа
        # Формат: <Зачарование>:<уровень>
        enchants:
          sharpness: 8
          unbreaking: 5
          fire: 4
          knockback: 2
        # Шанс выпадения вещи (пересчитывается в процентах по формуле <шанс> / <сумма шансов всех вещей> * 100%)
        chance: 15
      item2:
        item: IRON_SWORD
        amount: 1
        name: §6Железный меч
        enchants:
          sharpness: 5
          unbreaking: 3
          knockback: 2
        chance: 35
      item3:
        item: STONE_SWORD
        amount: 1
        name: §eКаменный меч
        enchants:
          sharpness: 3
          unbreaking: 3
          knockback: 2
        chance: 65
      item4:
        item: BOW
        amount: 1
        name: §eЛук
        enchants:
          power: 3
          unbreaking: 3
          infinity: 1
        chance: 95
      item5:
        item: GOLDEN_APPLE
        name: §rЗолотое яблоко
        amount: 4
        chance: 155
      item6:
        item: ARROW
        name: §rСтрела
        amount: 16
        chance: 185
      item7:
        item: BONE
        name: §rКость
        amount: 8
        chance: 215
      item8:
        item: ROTTEN_FLESH
        name: §rЗомбятинка
        amount: 6
        chance: 235
# - - - - - - - - - - - - - - - - - - - - -
# Строки, которые выводятся в чат.
# Для добавления цвета используйте
# символ § (& не работает!)
# - - - - - - - - - - - - - - - - - - - - -
strings:
  itemsToDrop: 'Выпадающие предметы:'

  # Префикс сообщений.
  prefix: §3[RandomBox] §b

  # Сообщения от плагина.
  configReloaded: Настройки перезагружены.
  configResetted: Настройки сброшены.
  boxGiven: Коробка успешно выдана.
  itemsDropped: 'Вам выпали: '

  # Ошибки, выводимые в чат.
  noPermissions: У вас нет прав для выполнения этой команды.
  boxOpenError: 'Произошла ошибка при открытии коробки:'
  boxGiveError: 'Произошла ошибка при выдаче коробки:'

  # Подробные описания ошибок.
  notAPlayer: вы не игрок! (WTF?!).
  playerNotFound: игрок не найден.
  itemIsNotABox: вы должны держать в руках коробку.
  noSuchBox: в config.yml нет коробки с таким id.
  noPermissionsToOpen: у вас нет прав для открытия этой коробки.
  itemsParsingError: невозможно распарсить настройки вещей в config.yml.
  itemsCountMissing: в config.yml нет параметра itemsToSelectCount или он меньше 1.
  notEnoughSpace: недостаточно места в инвентаре.
  boxParsingError: не удалось распарсить настройки коробки.