# - - - - - - - - - - - - - - - - - - - - -
# Описание и настройка плагина на русском:
# rubukkit.org/threads/.83608/
# - - - - - - - - - - - - - - - - - - - - -
# Configuration file for RandomBox
# Plugin author: saharNooby
# - - - - - - - - - - - - - - - - - - - - -
# File format is YAML
# To check is file correct use
# http://yaml-online-parser.appspot.com/
# If you want reset settings,
# you can delete this file.
# - - - - - - - - - - - - - - - - - - - - -
# If this parameter is true, in the console
# will print messages, like calculated
# probabilities.
# - - - - - - - - - - - - - - - - - - - - -
debug: false
# - - - - - - - - - - - - - - - - - - - - -
# Use metrics. Site: http://mcstats.org
# - - - - - - - - - - - - - - - - - - - - -
metrics: true
# - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - -
boxEnchantment: protection
# - - - - - - - - - - - - - - - - - - - - -
# All boxes that available
# - - - - - - - - - - - - - - - - - - - - -
boxes:
  # Box id, must be a integer.
  # Please, use large numbers
  # to id does not intersect
  # with the standard data values.
  9901:
    # Item that represents a box.
    # Recommended item is STORAGE_MINECART.
    # If that item can be used (for example, minecart can be placed on rails),
    # then you can't use it, if item is a box.
    # You can use numeric or string id.
    boxItem: STORAGE_MINECART
    # Box name, can be colored with &<color code>
    boxName: '&6Warrior box'
    # Drop items amount
    itemsToSelectCount: 3
    # Check for permission randombox.open.<box id>
    checkPermission: false
    # Should box open, if player right-clicked on it?
    openWhenClicked: true
    # Enchant box?
    enchant: true
    # Box can't stack (if box item can stack by default)
    unstackable: true
    # Items that can drop
    items:
      # Some name
      item1:
        # Item id (numeric or string)
        item: DIAMOND_SWORD
        # Data value
        data: 0
        # Item amount
        amount: 1
        # Item name, can be colored with &<color code>
        # If there is no "name" parameter,
        # item will not added to list in box lore.
        name: '&cDiamond sword'
        # Item lore, can be colored with &<color code>
        # Format: every list item - 'item'
        # is another line.
        lore:
        - '&7This sword dropped'
        - '&7from a box.'
        # Enchants on item.
        # Format: <ench name>:<any level>
        enchants:
          sharpness: 8
          unbreaking: 5
          fire: 4
          knockback: 2
        # Probability of drop
        chance: 2
      item2:
        item: IRON_SWORD
        amount: 1
        name: '&6Iron sword'
        enchants:
          sharpness: 5
          unbreaking: 3
          knockback: 2
        chance: 3
      item3:
        item: STONE_SWORD
        amount: 1
        name: '&eStone sword'
        enchants:
          sharpness: 3
          unbreaking: 3
          knockback: 2
        chance: 4
      item4:
        item: BOW
        amount: 1
        name: '&eBow'
        enchants:
          power: 3
          unbreaking: 3
          infinity: 1
        chance: 6
      item5:
        item: GOLDEN_APPLE
        name: '&rGolden apple'
        amount: 4
        chance: 8
      item6:
        # If this section is presented,
        # when this item drop will be
        # executed specified commands.
        #
        # In this case, player will get
        # 10 levels.
        # If you want only execute
        # commands (without giving item),
        # set item id to 'AIR' or 0.
        commands:
          # Some name
          command1:
            # Command name without '/'
            # and arguments.
            # %player% will be replaced
            # with player name.
            line: 'xp give %player% 10L'
            # Execute command
            # from console or player
            fromConsole: true
        item: AIR
        name: '&rExp (10 lvl)'
        amount: 1
        chance: 30
      item7:
        commands:
          command1:
            line: 'xp give %player% 6L'
            fromConsole: true
        item: AIR
        name: '&rExp (6 lvl)'
        amount: 1
        chance: 35
      item8:
        commands:
          command1:
            line: 'xp give %player% 3L'
            fromConsole: true
        item: AIR
        name: '&rExp (3 lvl)'
        amount: 1
        chance: 45
# - - - - - - - - - - - - - - - - - - - - -
# Name of section with strings. You can
# add you own section and set "locale"
# parameter to it's name.
# - - - - - - - - - - - - - - - - - - - - -
# Default locales:
# en (English), ru (Русский)
# - - - - - - - - - - - - - - - - - - - - -
locale: en
strings:
  en:
    # - - - - - - - - - - - - - - - - - - - - -
    # Messages that printing in chat.
    # Can be colored with &<color code>.
    # Color codes:
    # minecraft.gamepedia.com/Formatting_codes
    # You can use & instead of §
    # - - - - - - - - - - - - - - - - - - - - -
    itemsToDrop: 'Drop items:'
    # - - - - - - - - - - - - - - - - - - - - -
    # Messages prefix
    prefix: '&3[&bRandomBox&3] &6'
    # - - - - - - - - - - - - - - - - - - - - -
    # Messages
    configReloaded: 'Config reloaded.'
    boxGiven: 'Box succesfully given.'
    itemsDropped: 'You got: '
    # - - - - - - - - - - - - - - - - - - - - -
    # General errors
    noPermissions: 'You don''t have permission to do that.'
    boxOpenError: 'Box open error'
    boxGiveError: 'Box give error'
    # - - - - - - - - - - - - - - - - - - - - -
    # Detailed errors
    
    # Nulls
    itemIsNULL: 'item is null!'
    sectionIsNULL: 'section is null!'
    
    # Box creation
    noSuchBox: 'there is no box in config with this id.'
    canNotParseBox: 'cant parse box options.'
    notABox: 'that is not a box.'
    convertError: 'box section name is not valid number.'
    selectCntLessThanOne: 'drop items count less than one or not specified.'
    noItemsSection: 'there is no section with items in config.'
    
    # Item creation
    chanceLessThanOne: 'one of items hasnt probability or it less than one.'
    invalidCommandSection: 'one of items has invalid commands section.'
    
    # Commands errors
    notAPlayer: 'you are not a player!'
    playerNotFound: 'player not found.'
    idMustBeNumerical: 'box id must be a number.'
    noPermissionsToOpen: 'you don''t have permisson to open that box.'
    notEnoughSpace: 'you inventory is full!'
  ru:
    itemsToDrop: 'Выпадающие предметы:'
    # - - - - - - - - - - - - - - - - - - - - -
    # Префикс сообщений.
    prefix: '&3[&bRandomBox&3] &6'
    # - - - - - - - - - - - - - - - - - - - - -
    # Сообщения от плагина.
    configReloaded: 'Настройки перезагружены.'
    boxGiven: 'Коробка успешно выдана.'
    itemsDropped: 'Вы получили: '
    # - - - - - - - - - - - - - - - - - - - - -
    # Ошибки, выводимые в чат.
    noPermissions: 'У вас нет прав для выполнения этой команды.'
    boxOpenError: 'Произошла ошибка при открытии коробки'
    boxGiveError: 'Произошла ошибка при выдаче коробки'
    # - - - - - - - - - - - - - - - - - - - - -
    # Подробные описания ошибок.
    
    # Null
    itemIsNULL: 'item is null!'
    sectionIsNULL: 'section is null!'
    
    # Создание коробки
    noSuchBox: 'в config.yml нет коробки с таким id.'
    canNotParseBox: 'не удалось распарсить настройки коробки.'
    notABox: 'это не коробка.'
    convertError: 'имя секции не является целым числом.'
    selectCntLessThanOne: 'количество выпадающих вещей меньше 1 или отсутствует.'
    noItemsSection: 'отсутствует секция с выпадающими вещами.'
    
    # Создание вещи
    chanceLessThanOne: 'шанс выпадения одной из вещей меньше 1 или отсутствует.'
    invalidCommandSection: 'для одной из вещей неверно задана выполняемая команда.'
    
    # Ошибки в выполнении команд
    notAPlayer: 'вы не игрок! (WTF?!).'
    playerNotFound: 'игрок не найден.'
    idMustBeNumerical: 'идентификатор коробки должен быть числом.'
    noPermissionsToOpen: 'у вас нет прав для открытия этой коробки.'
    notEnoughSpace: 'недостаточно места в инвентаре.'