name: RandomBox
description: Random boxes in Minecraft!
website: 'dev.bukkit.org/bukkit-plugins/random_box/'
main: saharnooby.randombox.RandomBox
version: 1.7
author: saharNooby
commands:
  randombox:
    description: Main plugin command.
    usage: '§3[§bRandomBox§3] §6Use /randombox <reload>'
    aliases: [rb]
  givebox:
    description: Give the box to player.
    usage: '§3[§bRandomBox§3] §6Use /givebox <player> <box id>'
  openbox:
    description: Open box that is in you hand.
    usage: '§3[§bRandomBox§3] §6bUse /openbox'
permissions:
  randombox.*:
    description: Allows you to do everything.
    default: op
    children:
      randombox.main: true
      randombox.main.reload: true
      randombox.openbox: true
      randombox.givebox: true
      randombox.infinitebox: true
      randombox.open.*: true
  randombox.main:
    description: Allows you to use /randombox command.
    default: op
  randombox.main.reload:
    description: Allows you to reload plugin config.
    default: op
  randombox.openbox:
    description: Allows you to open boxes.
    default: true
  randombox.givebox:
    description: Allows you to give boxes.
    default: op
  randombox.infinitebox:
    description: The box will not dissapear after opening.
    default: op